GET http://localhost:8080/user

###
POST http://localhost:8080/user
Content-Type: application/json

{
  "kakaoId": 123456789,
  "name": "김현이",
  "university": "공과대학",
  "department": "컴퓨터공학부",
  "major": "소프트웨어전공",
  "studentId": "2014003990",
  "joinDate": 1111111,
  "joinType": "2014년도 1학기 정기모집",
  "type": 6
}

###
PUT http://localhost:8080/user
Content-Type: application/json

{
  "kakaoId": 123456789,
  "name": "김현이",
  "type": 6
}

###
GET http://localhost:8080/user/123456789

###
DELETE http://localhost:8080/user
Content-Type: text/plain

123456789

###